---
- name: echo your password
  hosts: localhost
  vars:
         - password_string: 'P@ssword'
  tasks:
         - name: Echo via shell
           shell: echo 'Your password is {{ password_string }}'
           no_log: true

         - debug:
             msg: "{{ your_password }}"
             no-log: true
